server:
  servlet:
    context-path: /admin
  port: 8081
joinfaces:
  jsf:
    project-stage: Production
    facelets-suffix: .faces
    facelets-skip-comments: true
    state-saving-method: server
    enable-validate-whole-bean: true
    interpret-empty-string-submitted-values-as-null: true

  primefaces:
    theme: omega
    font-awesome: true
    transform-metadata: true
    client-side-validation: true
    uploader: auto
spring:
  messages:
    basename: framework-messages, admin-messages
  config:
    name:
  application:
    name: fast-admin
  profiles:
    active: @profileActive@
  datasource:
    dynamic:
      druid:
        initial-size: 10
        max-active: 100
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #Oracle需要打开注释
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false

mybatis-plus:
  type-aliases-package: pers.dandandog.**.entity
  typeEnumsPackage: pers.dandandog.**.entity.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
fast-code:
  map-struct:
    url-domain: https://www.myelephant.cn