server:
  servlet:
    context-path: /admin
spring:
  application:
    name: fast-admin
  profiles:
    active: @profileActive@
fast-code:
  swagger:
    api-scans:
      - group-name: admin
        base-package: pers.dandandog.admin.controller
        base-path: /test/hello
  map-struct:
    url-domain: https://www.myelephant.cn